---
title: Demo
author: Mamut
date: '2020-12-24'
slug: []
categories:
  - R
tags:
  - R Markdown
  - hugo
authors: []
description: ''
externalLink: ''
series: []
---

```{r setup, include=FALSE}
options(scipen = 999999)
knitr::opts_chunk$set(echo = TRUE)
source("functions.r")
library(tidymodels)
library(modeltime)
library(tidyverse)
library(lubridate)
library(timetk)
library(ggExtra)
library(gridExtra)
gg.gauge <- function(pos,breaks=c(0,30,70,100)) {
  require(ggplot2)
  get.poly <- function(a,b,r1=0.5,r2=1.0) {
    th.start <- pi*(1-a/100)
    th.end   <- pi*(1-b/100)
    th       <- seq(th.start,th.end,length=100)
    x        <- c(r1*cos(th),rev(r2*cos(th)))
    y        <- c(r1*sin(th),rev(r2*sin(th)))
    return(data.frame(x,y))
  }
  ggplot()+ 
    geom_polygon(data=get.poly(breaks[1],breaks[2]),aes(x,y),fill="red")+
    geom_polygon(data=get.poly(breaks[2],breaks[3]),aes(x,y),fill="gold")+
    geom_polygon(data=get.poly(breaks[3],breaks[4]),aes(x,y),fill="forestgreen")+
    geom_polygon(data=get.poly(pos-1,pos+1,0.2),aes(x,y))+
    geom_text(data=as.data.frame(breaks), size=5, fontface="bold", vjust=0,
              aes(x=1.1*cos(pi*(1-breaks/100)),y=1.1*sin(pi*(1-breaks/100)),label=paste0(breaks,"%")))+
    annotate("text",x=0,y=0,label=pos,vjust=0,size=8,fontface="bold")+
    coord_fixed()+
    theme_bw()+
    theme(axis.text=element_blank(),
          axis.title=element_blank(),
          axis.ticks=element_blank(),
          panel.grid=element_blank(),
          panel.border=element_blank()) 
}
settings <- list() 
settings$ensembleModels <- c("ARIMA", "ETS", "STL", "ARIMA LogTr")
settings$packages <- list("tidyverse", "lubridate", "formattable",
                          "flexdashboard")
lapply(settings$packages, library, character.only = TRUE)
theme_set(theme_light())
```
```{r settings, include=FALSE}
mmtData <- readRDS("render data/mmt.rds")
stock <- mmtData$stock
data <- mmtData$data
stt <- mmtData$stats
validation <- mmtData$validation
tst2 <- mmtData$tst2
tmp_clean <- mmtData$tmp_clean
dt1 <- mmtData$dt1
predicted_price_change <- mmtData$predicted_price_change
tmp_sp3 <- mmtData$tmp_sp3
xgbData <- mmtData$xgbData
dt2 <- mmtData$dt2
scoring_prob <- mmtData$scoring_prob
scores_fix_p <- mmtData$scores_fix_p
tst <- mmtData$tst
tmp_formattable <- mmtData$tmp_formattable
tmp002 <- mmtData$tmp002
stt <- mmtData$stt
improvement_formatter <- 
  formatter("span", 
            style = x ~ style(
              font.weight = "bold", 
              color = ifelse(x > 0, "#7EDB76",
                             ifelse(x < 0, "#F94A2E", 
                                    "black"))))
dtt1 <-   dt1 %>% 
    dplyr::select(-open, -high) %>% 
    mutate(`Next day price` = close + `Validated change [$]`) %>% 
    rename(`Day close price` = close)
prov_det <- dt1 %>% 
  mutate(date = as.Date(substr(Time, 1, 10))) %>% 
  group_by(date) %>% 
  summarise(provider_names = paste(unique(`Text provider`), collapse = ", ")) %>% 
  ungroup()
```

## Last signals {.tabset}
```{r signalslast1, echo=FALSE, warning=FALSE, message=FALSE}
formattable(
  dt1 %>% 
    head(3) %>% 
    arrange(desc(Time)) %>% 
    dplyr::select(Time, `NLP Signal`, `NLP Signal price`, `Text provider`),
  align = c("r", rep("l",6)),
            list(Time = formatter("span", 
                                 style = ~ style(color = "black", 
                                                 font.weight = "bold")),
               `NLP Signal`  = improvement_formatter)
)
```

### Smart Bubbles
```{r signals counter, echo = F, warning=F, message=F}
plotly::ggplotly(
tmp_sp3 %>% 
  mutate(
         `NLP signals` = signals_down + signals_up) %>% 
  rename(`Price change [% validated]` = price_change_perc,
         `Day close price` = close) %>% 
  ggplot(aes(x = date)) +
    geom_line(aes(y = low), color = "#FFC9B2", .alpha = .3)+
  geom_line(aes(y = high), color = "#D7FFC8", alpha = .5)+
  geom_point(aes(y = `Day close price`, 
                 size = `NLP signals`, 
                 label = providers,
                 #label2 = `Next price`,
                 label3 = signals_up,
                 label4 = signals_down,
                 color = `Price change [% validated]`)) +
    geom_line(aes(y = `Day close price`)) +
  theme(legend.position="none") +
  labs(title = "",
       x = "Date",
       y = "Stock price") +
scale_colour_gradient2(
  low = "red",
  mid = "#9C9C9C",
  high = "green",
  midpoint = 0,
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour"
) + 
  scale_x_date(limits = c(max(tmp_sp3$date) - 360, max(tmp_sp3$date)))
)
```

### Providers scores
```{r signals summary2 , echo=FALSE, warning=FALSE, message=FALSE}
tstst <- tst %>% 
  group_by(`Text provider`) %>% 
  mutate(`Last mean predicted change [$]` = ifelse(`Provider signals` == max(`Provider signals`), `Mean score`, NA),
         `Last mean score date` = ifelse(`Provider signals` == max(`Provider signals`), `date`, NA)) %>% 
  mutate(`Last mean predicted change [$]` = ifelse(`Provider texts` == max(`Provider texts`), `Last mean predicted change [$]`, NA)) %>% 
  ungroup() 
plotly::ggplotly(
tstst %>% 
  ggplot(aes(x = date)) +
  geom_line(aes(y = `Mean score`,
                 label1 = `Next day score`,
                 label = `Provider texts`,
                 label2 = `Provider signals`,
                group = `Text provider`),
            color = "#796490",
            linetype = "dotdash") +
  geom_point(aes(y = `Last mean predicted change [$]`, 
                 size = `Provider signals`,
                 color = `Text provider`,
                 label = `Provider texts`)) +
  labs(color = "Provider",
       size = "",
       y = "Mean predicted price change [$]")
)
 
```

### Table
```{r last signals, echo = F, warning=F, message=F}
formattable(
dtt1 %>% 
  dplyr::select(Time, `NLP Signal`, `NLP Signal price`, 
                `Day close price`, `Next day price`, 
                `Validated change [$]`, `Validated change [%]`,
                `Text provider`, url) %>% 
  rename(`Signal provider` = `Text provider`,
         Text = url),
  align = c("r", rep("l",6)),
            list(Time = formatter("span", 
                                 style = ~ style(color = "black", 
                                                 font.weight = "bold")),
               `NLP Signal`  = improvement_formatter,
               `NLP Signal price` = stock$imp_formatters$mp,
`Day close price` = stock$imp_formatters$cc2,
`Validated change [$]` = improvement_formatter,
`Next day price` = stock$imp_formatters$cc2,
`Validated change [%]` = improvement_formatter)
)
```

### NLP scores (validated price changes) | NLP scoring probabilty
```{r accuracy, echo=FALSE, warning=FALSE, message=FALSE}
scores <- gauge(predicted_price_change, min = 0, max = 100, symbol = '%', 
      gaugeSectors(
  success = c(65, 100), warning = c(30, 64), danger = c(0, 29)
))

probabilty <- gauge(round(scoring_prob*100,2), min = 0, max = 100, symbol = '%', 
      gaugeSectors(
  success = c(65, 100), warning = c(30, 64), danger = c(0, 29)
))


```

<div class = "row">
<div class = "col-md-6">
<center>
```{r gauge, fig.width=2, fig.height=2}
scores
```
</center>
</div>

<div class = "col-md-6">
<center>    
```{r gauge2, fig.width=2, fig.height=2}
probabilty
```    
</center>
</div>
</div>


### NLP `r paste("Last signals:", sum(dt2$Signals))`
```{r tfsignals, echo=FALSE, warning=FALSE, message=FALSE}
plotly::ggplotly(
dt2 %>% 
  mutate(`NLP Signal` = as.factor(`NLP Signal`),
         `Signal validation` = as.factor(`Signal validation`)) %>% 
  ggplot(aes(x = `Signal validation`, y = `NLP Signal`)) +
  geom_point(aes(size =Signals, color = `Validated price change [$]`)) +
  scale_colour_gradient2(
  low = "red",
  mid = "#9C9C9C",
  high = "green",
  midpoint = 0,
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour"
) +
  theme(legend.position="none") +
  labs(title = " ")
)
```


### Available articles
```{r articles, echo = F, warning=F, message=F}
# table with articles
DT::datatable(tmp_clean ,
              filter = "top",
  rownames = FALSE)
```

## Price Analysis {.tabset}
### Forecast
```{r xgb1, echo=FALSE,  warning=FALSE, message=FALSE}
plotly::ggplotly(
xgbData$forecasts %>% 
  filter(dateTime >= Sys.Date()-lubridate::days(120)) %>% 
  rename(`Stock price` = actual) %>% 
  mutate(horizon = ifelse(horizon == "actual",
                          "historical data",
                          "forecasted data")) %>% 
  ggplot(aes(x = dateTime)) + 
  geom_point(aes(y = `Stock price`,
                 label = signals,
                 label1 = up,
                 label2 = down,
                 color = horizon)) +
    geom_line(aes(y = `Stock price`)) +
  theme(legend.position="none") +
  labs(title = "XGBoost",
       x = "",
       y = "Stock Price")  +
  scale_color_manual(values=c("#15BCF0", "#6B767A"))
)
```

### Financial statement
```{r fin statement, echo=FALSE,  warning=FALSE, message=FALSE}
DT::datatable(stt$financial_statement$yahoo,
   rownames = FALSE,
  extensions = "Buttons",
  options = list(
    dom = "t",
    buttons = c("csv", "excel"),
    pageLength = nrow(stt$financial_statement$yahoo)
  )) 
```



### Historical prices
```{r indtradaymodels_dt , echo=FALSE, warning=FALSE, message=FALSE}
DT::datatable(stt$summary$intraday %>% 
                renameSummary2(),
  filter = "top",
  rownames = FALSE) %>% 
 DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[2],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[2]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[2]))) %>% 
   DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[3],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[3]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[3]))) %>%  
  DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[4],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[4]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[4]))) %>%  
  DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[5],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[5]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[5]))) %>% 
   DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[6],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[6]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[6]))) %>% 
   DT::formatStyle(
    names(stt$summary$intraday %>% 
                renameSummary2())[7],
    backgroundColor = DT::styleInterval(
      color_table_points(stt$summary$intraday%>% 
                renameSummary2(),
                        names(stt$summary$intraday %>% 
                renameSummary2())[7]),
      color_table(stt$summary$intraday%>% 
                renameSummary2(),
                names(stt$summary$intraday %>% 
                renameSummary2())[7]))) 
```

Report ID:

`r stock$render$reportName`
`r stock$render$dataStamp`
[link to SignalsHub](https://mamut.shinyapps.io/providers/)

